services:
  db:
    image: mysql:latest
    container_name: mysql_pokerank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokerank_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
